# default configuration
baseURL = "https://profile.zhangchi.fun"
languageCode = "zh-cn"
summaryLength = "10"
theme = "kross-hugo"
title = "张驰"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
#[[menu.main]]
#URL = "#skill"
#name = "Skills"
#weight = 1

[[menu.main]]
URL = "https://blog.zhangchi.fun"
name = "Blog"
weight = 2

#[[menu.main]]
#URL = "portfolio"
#name = "Portfolio"
#weight = 3

#[[menu.main]]
#URL = "contact"
#name = "Contact"
#weight = 4


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#41228e"
# contact info
phone = ""
qq = "574174937"
email = "zliming@outlook.com"
address = "山东省济南市"
# meta description
author = "张驰"
description = "张驰 软件工程师"
# google analytics
google_analytics_id = "G-NXK10QCHTR" # Your ID
baidu_analytics_id = "9a9634f2779435bfd7dce99f17a9b955"
baidu_site_verification = "code-tjdyPSR8G5"
baidu_auto_push = true
# copyright
copyright = "Copyright &copy; 2021 张驰"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
# gmap_api = ""
# map_latitude = "51.5223477"
# map_longitude = "-0.1622023"
# map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-github"
URL = "https://github.com/realZhangChi"

[[params.social]]
icon = "ti-heart"
URL = "https://blog.zhangchi.fun"
